ARG ALPINE_VERSION=3.21
FROM alpine:${ALPINE_VERSION}
LABEL Maintainer="Digital Curation Centre (UK)"
LABEL Description="DMPsee container php-nginx based on Alpine Linux."

# Setup document root
WORKDIR /var/www/html

# Install packages and remove default server definition
RUN apk add --no-cache \
  bash \
  curl \
  nginx \
  php84 \
  php84-ctype \
  php84-curl \
  php84-dom \
  php84-fileinfo \
  php84-fpm \
  php84-gd \
  php84-intl \
  php84-mbstring \
  php84-pgsql \
  php84-opcache \
  php84-openssl \
  php84-posix \
  php84-session \
  php84-tokenizer \
  php84-xml \
  php84-xmlreader \
  php84-xmlwriter \
  supervisor

RUN ln -s /usr/bin/php84 /usr/bin/php

# Copy SSL certificates
COPY config/ssl/dmpsee.* /etc/ssl/

# Configure nginx
RUN sed -i 's#access_log /var/log/nginx/access.log main;#access_log /dev/stdout main;#' /etc/nginx/nginx.conf
RUN sed -i 's#error_log /var/log/nginx/error.log warn;#error_log /dev/stderr notice;#' /etc/nginx/nginx.conf
COPY config/http.d/default.conf /etc/nginx/http.d/

# Configure php-fpm
RUN sed -i 's#;error_log = log/php84/error.log#error_log = /dev/stderr#' /etc/php84/php-fpm.conf

# Copy default test file
COPY www/test.php /var/www/html

# COPY config/nginx.conf /etc/nginx/nginx.conf

# Configure nginx - default server
#COPY config/conf.d /etc/nginx/conf.d/

# Configure PHP-FPM
ENV PHP_INI_DIR=/etc/php84
# COPY config/fpm-pool.conf ${PHP_INI_DIR}/php-fpm.d/www.conf
# COPY config/php.ini ${PHP_INI_DIR}/conf.d/custom.ini

# Configure supervisord
COPY config/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Make sure files/folders needed by the processes are accessable when they run under the nobody user
# RUN chown -R nobody:nobody /var/www/html /run /var/lib/nginx /var/log/nginx

# Switch to use a non-root user from here on
# USER nobody

# Add application
# COPY --chown=nobody src/ /var/www/html/

# Expose the port nginx is reachable on
EXPOSE 80 443

# Let supervisord start nginx & php-fpm
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

# Configure a healthcheck to validate that everything is up&running
# HEALTHCHECK --timeout=10s CMD curl --silent --fail http://127.0.0.1:8080/fpm-ping || exit 1