ARG ALPINE_VERSION=3.22

FROM alpine:${ALPINE_VERSION}
LABEL Maintainer="Digital Curation Centre (UK)"
LABEL Description="Vaquita Dispatch container"

# Install packages and remove default server definition
RUN apk add --no-cache \
  bash \
  curl \
  php84 \
  php84-ctype \
  php84-curl \
  php84-dom \
  php84-fileinfo \
  php84-fpm \
  php84-gd \
  php84-intl \
  php84-mbstring \
  php84-pgsql \
  php84-opcache \
  php84-openssl \
  php84-posix \
  php84-session \
  php84-tokenizer \
  php84-xml \
  php84-xmlreader \
  php84-xmlwriter \
  supervisor

RUN ln -s /usr/bin/php84 /usr/bin/php

RUN mkdir -p /opt/vaquita

# Configure PHP-FPM
ENV PHP_INI_DIR=/etc/php84

WORKDIR /opt/vaquita

CMD ["tail", "-f", "/dev/null"]