ARG ALPINE_VERSION=3.22

FROM alpine:${ALPINE_VERSION}
LABEL Maintainer="Digital Curation Centre (UK)"
LABEL Description="vaquita API container"

# Install packages and remove default server definition
RUN apk add --no-cache \
  bash \
  curl \
  nginx \
  php84 \
  php84-ctype \
  php84-curl \
  php84-dom \
  php84-fileinfo \
  php84-fpm \
  php84-gd \
  php84-intl \
  php84-mbstring \
  php84-pgsql \
  php84-opcache \
  php84-openssl \
  php84-posix \
  php84-session \
  php84-tokenizer \
  php84-xml \
  php84-xmlreader \
  php84-xmlwriter \
  supervisor

RUN ln -s /usr/bin/php84 /usr/bin/php

# Copy SSL certificates
COPY config/ssl/vaquita.* /etc/ssl/

# Configure nginx
RUN sed -i 's#access_log /var/log/nginx/access.log main;#access_log /dev/stdout main;#' /etc/nginx/nginx.conf
RUN sed -i 's#error_log /var/log/nginx/error.log warn;#error_log /dev/stderr notice;#' /etc/nginx/nginx.conf
COPY config/http.d/default.conf /etc/nginx/http.d/
COPY config/http.d/vaquita-api.conf /etc/nginx/http.d/

# Configure php-fpm
RUN sed -i 's#;error_log = log/php84/error.log#error_log = /dev/stderr#' /etc/php84/php-fpm.conf

# Copy default test file
COPY www/test.php /var/www/html/

RUN mkdir -p \
  /opt/vaquita

# Configure PHP-FPM
ENV PHP_INI_DIR=/etc/php84

# Configure supervisord
COPY config/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

EXPOSE 80 443

WORKDIR /opt/vaquita

# Let supervisord start nginx & php-fpm
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
